# Dependencies
markdown:         kramdown

redcarpet:
  extensions:     ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

highlighter:      rouge


# Permalinks
permalink:        pretty

# Setup
title:            MorningDip
tagline:          'rest@rea'
description:      '紀錄那些我所知道的大小事'
url:              https://morningdip.github.io/
baseurl:          /

author:
  name:           'Eric Chen'
  url:            


gems:             ["jekyll-paginate"]
paginate:         5

# Custom vars
version:          1.0.0

github:           https://github.com/morningdip